### ISSUE TITLE
Check the author of this book

### ISSUE THREAD

**Issue by 1iyiwei** [ShenCiao/brush-rendering-tutorial#5]
https://github.com/ShenCiao/brush-rendering-tutorial/blob/68cbfb887f832c660d370b65a82dd36bdde9ae7a/docs/Introduction/Introduction.mdx#L39

**Comment by ShenCiao** [comment]
The second chapter is written by Stephen DiVerdi, but the book is edited by Paul Rosin and John Collomosse.
I misunderstood and will modify it.

**Comment by ShenCiao** [comment]
#Fix
